# Generated by Django 3.2.15 on 2023-02-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=30)),
                ('contact_number', models.IntegerField()),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'register',
                'managed': False,
            },
        ),
    ]
