# Generated by Django 3.2.15 on 2023-02-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('working_time', models.CharField(max_length=60)),
                ('more_information', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(max_length=45)),
                ('facilities', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=1000)),
                ('amount', models.IntegerField()),
                ('booking_status', models.CharField(max_length=45)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
    ]
