# Generated by Django 3.2.15 on 2023-02-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('deliverystatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'delivery_status',
                'managed': False,
            },
        ),
    ]
