# Generated by Django 3.2.15 on 2023-02-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.IntegerField()),
                ('contact_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(max_length=45)),
                ('ifsc_code', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
