# Generated by Django 3.2.15 on 2023-02-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('ads_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=35)),
                ('product_image', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'advertisement',
                'managed': False,
            },
        ),
    ]
