# Generated by Django 3.2.15 on 2023-02-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facilities_id', models.IntegerField(primary_key=True, serialize=False)),
                ('equipments', models.CharField(max_length=30)),
                ('special_features', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'facilities',
                'managed': False,
            },
        ),
    ]
